[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--no-entry",
    "-C", "link-arg=--export-dynamic",
]

[env]
CC = { value = "clang-wasm", force = true }
CXX = { value = "clang++-wasm", force = true }
